<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.SqlServer" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClaimsModule.Application\ClaimsModule.Application.csproj" />
    <ProjectReference Include="..\ClaimsModule.Infrastructure\ClaimsModule.Infrastructure.csproj" />
    <ProjectReference Include="..\ClaimsModule.Persistence\ClaimsModule.Persistence.csproj" />
  </ItemGroup>

</Project>
