namespace ClaimsModule.Domain.Enums;

public enum AuditEventType
{
    CLAIM_CREATED,
    STATUS_CHANGED,
    PARTY_ADDED,
    PARTY_REMOVED,
    RESERVE_CREATED,
    RESERVE_AUTO_APPROVED,
    RESERVE_APPROVED,
    RESERVE_REJECTED,
    RESERVE_RETRACTED,
    RESERVE_OVERRIDE_SET,
    GL_POSTING_SIMULATED,
    GL_POSTING_FAILED,
    DOCUMENT_UPLOADED,
    CLAIM_CLOSED,
    CLAIM_REOPENED,
    SLA_BREACH_DETECTED,
    VALIDATION_ISSUE_ADDED
}
